version: '2.1'

volumes:
  db_data:
    external: true
  db_backup:
    external: true
services:
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_PASSWORD=123123
      - POSTGRES_USER=evgen
      - POSTGRES_DB=test_db
    volumes:
      - ./db_data:/etc/postgresql/data
      - ./db_backup:/etc/postgresql/backup
    ports:
      - ${POSTGRES_PORT:-5432}:5432